# Generated by Django 6.0.3 on 2026-03-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_template', models.CharField(default='Festeggiati di oggi - {date}', max_length=255)),
                ('body_template', models.TextField(default='Buongiorno,\n\nEcco chi compie gli anni oggi:\n{employees}\n\nFai loro gli auguri!', help_text='Template testo email. Usa {employees} e {date} come placeholder.')),
                ('sender_email', models.EmailField(blank=True, help_text='Indirizzo mittente. Se vuoto, viene usato DEFAULT_FROM_EMAIL.', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email config',
                'verbose_name_plural': 'Email configs',
            },
        ),
    ]
